// data/products.ts
import { IProduct, ProductCategory, BadgeColor } from '@/config/types'

export const allProducts: IProduct[] = [
	// ==================== COMBOS ====================
	{
		id: 1,
		internalId: 'combo-big-burger',
		category: ProductCategory.COMBO,
		name: 'Big Burger Combo',
		description: 'Hamburguesa XL, papas fritas y bebida',
		price: 12.50,
		image: 'https://foodish-api.com/images/burger/burger1.jpg',
		badge: 'XL',
		badgeColor: BadgeColor.PRIMARY,
		rating: 4.9,
		calories: 1200,
		ingredients: [
			'Hamburguesa XL',
			'Papas Fritas',
			'Bebida 350ml',
			'Carne Premium',
			'Vegetales Frescos',
			'Salsa Especial',
		],
	},
	{
		id: 2,
		internalId: 'combo-burger',
		category: ProductCategory.COMBO,
		name: 'Burger Combo',
		description: 'Hamburguesa clásica y bebida',
		price: 8.50,
		image: 'https://foodish-api.com/images/burger/burger2.jpg',
		badge: 'Popular',
		badgeColor: BadgeColor.ORANGE,
		rating: 4.7,
		calories: 850,
		ingredients: [
			'Hamburguesa Clásica',
			'Bebida 350ml',
			'Carne Premium',
			'Lechuga',
			'Tomate',
			'Queso',
		],
	},
	{
		id: 3,
		internalId: 'combo-sandwich',
		category: ProductCategory.COMBO,
		name: 'Sandwich Combo',
		description: 'Sandwich artesanal y bebida',
		price: 7.50,
		image: 'https://foodish-api.com/images/samosa/samosa1.jpg',
		rating: 4.5,
		calories: 720,
		ingredients: [
			'Sandwich Artesanal',
			'Bebida 350ml',
			'Pan Horneado',
			'Jamón',
			'Queso',
			'Vegetales',
		],
	},
	{
		id: 4,
		internalId: 'combo-popcorn',
		category: ProductCategory.COMBO,
		name: 'Popcorn Combo',
		description: 'Palomitas de maíz grandes y bebida',
		price: 5.00,
		image: 'https://foodish-api.com/images/rice/rice1.jpg',
		badge: 'Económico',
		badgeColor: BadgeColor.EMERALD,
		rating: 4.3,
		calories: 450,
		ingredients: [
			'Palomitas Grandes',
			'Bebida 350ml',
			'Maíz Premium',
			'Mantequilla',
			'Sal',
		],
	},

	// ==================== BURGERS ====================
	{
		id: 5,
		internalId: 'hamburguesa-individual',
		category: ProductCategory.BURGER,
		name: 'Hamburguesa Individual',
		description: 'Carne premium y vegetales frescos',
		price: 6.00,
		image: 'https://foodish-api.com/images/burger/burger3.jpg',
		rating: 4.8,
		calories: 680,
		ingredients: [
			'Carne Premium',
			'Pan Artesanal',
			'Lechuga',
			'Tomate',
			'Cebolla',
			'Salsa Especial',
		],
	},
	{
		id: 6,
		internalId: 'cheeseburger-doble',
		category: ProductCategory.BURGER,
		name: 'Double Cheeseburger',
		description: 'Doble carne, doble queso',
		price: 8.00,
		image: 'https://foodish-api.com/images/burger/burger4.jpg',
		badge: 'Bestseller',
		badgeColor: BadgeColor.PRIMARY,
		rating: 4.9,
		calories: 920,
		ingredients: [
			'Doble Carne Premium',
			'Doble Queso Cheddar',
			'Lechuga',
			'Tomate',
			'Pepinillos',
			'Salsa Especial',
		],
	},

	// ==================== PANES ====================
	{
		id: 7,
		internalId: 'pan-estrella',
		category: ProductCategory.BREAD,
		name: 'Pan Estrella',
		description: 'Nuestra especialidad de la casa',
		price: 2.50,
		image: 'https://foodish-api.com/images/dosa/dosa1.jpg',
		badge: 'Especialidad',
		badgeColor: BadgeColor.PRIMARY,
		rating: 4.9,
		calories: 280,
		ingredients: [
			'Harina Premium',
			'Levadura Natural',
			'Mantequilla',
			'Huevos Frescos',
			'Azúcar',
		],
	},
	{
		id: 8,
		internalId: 'croissant',
		category: ProductCategory.BREAD,
		name: 'Croissant',
		description: 'Crujiente y mantequilloso',
		price: 3.00,
		image: 'https://foodish-api.com/images/dosa/dosa2.jpg',
		rating: 4.8,
		calories: 320,
		ingredients: [
			'Masa Hojaldrada',
			'Mantequilla Francesa',
			'Harina de Trigo',
			'Levadura',
		],
	},
	{
		id: 9,
		internalId: 'pan-sandwich',
		category: ProductCategory.BREAD,
		name: 'Pan Sándwich',
		description: 'Horneado diariamente',
		price: 2.00,
		image: 'https://foodish-api.com/images/dosa/dosa3.jpg',
		rating: 4.6,
		calories: 250,
		ingredients: [
			'Harina Integral',
			'Levadura',
			'Aceite de Oliva',
			'Sal Marina',
		],
	},

	// ==================== BEBIDAS ====================
	{
		id: 10,
		internalId: 'coca-cola',
		category: ProductCategory.DRINK,
		name: 'Coca-Cola',
		description: 'Clásica y refrescante - 350ml',
		price: 2.00,
		image: 'https://foodish-api.com/images/rice/rice2.jpg',
		badge: 'Clásica',
		badgeColor: BadgeColor.PRIMARY,
		rating: 4.9,
		calories: 140,
		ingredients: [
			'Agua Carbonatada',
			'Azúcar',
			'Caramelo',
			'Cafeína',
		],
	},
	{
		id: 11,
		internalId: 'pepsi',
		category: ProductCategory.DRINK,
		name: 'Pepsi',
		description: 'Refrescante sabor cola - 350ml',
		price: 2.00,
		image: 'https://foodish-api.com/images/rice/rice3.jpg',
		rating: 4.7,
		calories: 150,
		ingredients: [
			'Agua Carbonatada',
			'Azúcar',
			'Caramelo',
			'Cafeína',
		],
	},
	{
		id: 12,
		internalId: 'seven-up',
		category: ProductCategory.DRINK,
		name: 'Seven Up',
		description: 'Limón-lima refrescante - 350ml',
		price: 2.00,
		image: 'https://foodish-api.com/images/rice/rice4.jpg',
		rating: 4.6,
		calories: 130,
		ingredients: [
			'Agua Carbonatada',
			'Azúcar',
			'Ácido Cítrico',
			'Sabor Natural',
		],
	},
	{
		id: 13,
		internalId: 'uva',
		category: ProductCategory.DRINK,
		name: 'Uva',
		description: 'Sabor frutal de uva - 350ml',
		price: 2.00,
		image: 'https://foodish-api.com/images/rice/rice5.jpg',
		badge: 'Frutal',
		badgeColor: BadgeColor.EMERALD,
		rating: 4.5,
		calories: 145,
		ingredients: [
			'Agua Carbonatada',
			'Azúcar',
			'Sabor a Uva',
			'Colorante Natural',
		],
	},
	{
		id: 14,
		internalId: 'naranja',
		category: ProductCategory.DRINK,
		name: 'Naranja',
		description: 'Sabor cítrico refrescante - 350ml',
		price: 2.00,
		image: 'https://foodish-api.com/images/rice/rice6.jpg',
		rating: 4.7,
		calories: 135,
		ingredients: [
			'Agua Carbonatada',
			'Azúcar',
			'Sabor a Naranja',
			'Vitamina C',
		],
	},

	// ==================== HELADOS ====================
	{
		id: 15,
		internalId: 'paleta-choco',
		category: ProductCategory.ICECREAM,
		name: 'Paleta Chocomaní',
		description: 'Chocolate con maní crujiente',
		price: 1.00,
		image: 'https://foodish-api.com/images/dessert/dessert1.jpg',
		badge: 'Popular',
		badgeColor: BadgeColor.ORANGE,
		rating: 4.8,
		calories: 150,
		ingredients: [
			'Chocolate',
			'Maní Crujiente',
			'Crema de Helado',
		],
	},
	{
		id: 16,
		internalId: 'paleta-limon',
		category: ProductCategory.ICECREAM,
		name: 'Paleta Limón',
		description: 'Refrescante sabor cítrico',
		price: 1.00,
		image: 'https://foodish-api.com/images/dessert/dessert2.jpg',
		rating: 4.6,
		calories: 120,
		ingredients: [
			'Jugo de Limón',
			'Azúcar',
			'Agua Purificada',
		],
	},
	{
		id: 17,
		internalId: 'paleta-sandia',
		category: ProductCategory.ICECREAM,
		name: 'Paleta Sandía',
		description: 'Dulce y refrescante',
		price: 1.00,
		image: 'https://foodish-api.com/images/dessert/dessert3.jpg',
		rating: 4.7,
		calories: 110,
		ingredients: [
			'Pulpa de Sandía',
			'Azúcar',
			'Agua',
		],
	},
	{
		id: 18,
		internalId: 'helado-fresa',
		category: ProductCategory.ICECREAM,
		name: 'Helado de Fresa',
		description: 'Cremoso sabor a fresa',
		price: 1.50,
		image: 'https://foodish-api.com/images/dessert/dessert4.jpg',
		badge: 'Cremoso',
		badgeColor: BadgeColor.PRIMARY,
		rating: 4.9,
		calories: 190,
		ingredients: [
			'Crema de Leche',
			'Fresas Naturales',
			'Azúcar',
			'Vainilla',
		],
	},
	{
		id: 19,
		internalId: 'helado-pistacho',
		category: ProductCategory.ICECREAM,
		name: 'Helado de Pistacho',
		description: 'Sabor único y delicioso',
		price: 1.50,
		image: 'https://foodish-api.com/images/dessert/dessert5.jpg',
		badge: 'Premium',
		badgeColor: BadgeColor.EMERALD,
		rating: 4.7,
		calories: 210,
		ingredients: [
			'Crema de Leche',
			'Pistachos Naturales',
			'Azúcar',
			'Extracto Natural',
		],
	},

	// ==================== POSTRES ====================
	{
		id: 20,
		internalId: 'torta-milk-pink',
		category: ProductCategory.DESSERT,
		name: 'Torta Milk Pink',
		description: 'Porción individual de nuestra especialidad',
		price: 1.00,
		image: 'https://foodish-api.com/images/dessert/dessert6.jpg',
		badge: 'Especialidad',
		badgeColor: BadgeColor.PRIMARY,
		rating: 4.9,
		calories: 260,
		ingredients: [
			'Bizcocho de Vainilla',
			'Crema Pink',
			'Leche Condensada',
			'Decoración Pink',
		],
	},
	{
		id: 21,
		internalId: 'cupcake-vainilla',
		category: ProductCategory.DESSERT,
		name: 'Cupcake Vainilla',
		description: 'Suave y esponjoso',
		price: 1.00,
		image: 'https://foodish-api.com/images/dessert/dessert7.jpg',
		rating: 4.7,
		calories: 220,
		ingredients: [
			'Bizcocho de Vainilla',
			'Frosting de Vainilla',
			'Azúcar Glass',
			'Decoración',
		],
	},

	// ==================== SNACKS ====================
	{
		id: 22,
		internalId: 'papas-fritas',
		category: ProductCategory.SNACK,
		name: 'Papas Fritas',
		description: 'Crujientes y en su punto de sal',
		price: 3.50,
		image: 'https://foodish-api.com/images/samosa/samosa2.jpg',
		badge: 'Crujientes',
		badgeColor: BadgeColor.ORANGE,
		rating: 4.7,
		calories: 420,
		ingredients: [
			'Papas Premium',
			'Aceite Vegetal',
			'Sal Marina',
			'Condimentos',
		],
	},
	{
		id: 23,
		internalId: 'popcorn-individual',
		category: ProductCategory.SNACK,
		name: 'Popcorn',
		description: 'Palomitas de maíz recién explotadas',
		price: 3.00,
		image: 'https://foodish-api.com/images/rice/rice7.jpg',
		rating: 4.5,
		calories: 350,
		ingredients: [
			'Maíz Premium',
			'Mantequilla',
			'Sal',
		],
	},
]