// data/mockProducts.ts
import { ICatalog } from './types'

export const burgersCatalog: ICatalog = {
    id: 'burgers',
    title: 'Hamburguesas Gourmet',
    subtitle: 'Nuestra mejor selección de hamburguesas artesanales',
    products: [
        {
            id: '1',
            name: 'Hamburguesa Clásica con Queso',
            description: 'Carne de res de primera, cheddar añejo, lechuga de mantequilla y nuestra salsa secreta.',
            price: 12.99,
            image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBdfcZ28n1UP8eiyxAl2jy_A04xnpDf9U1agZtuDh4m5xHyHAHVQFDXAeoIuZ-HUamnM3ZXo01awMIsQumH9BVeEGbTNH9YfMeGp5owjvrY2u49iM9GNkLM5Ldn5v4u4QwuzG-tXTTSjQJzEc219T-szOOPlI61GnznGEcHY0OIvfMNm6MMXKdRLrvIXVgb7CFaL8Us4gi_1lMtHDywL5yL_hTi1Jwxd2K9rvrEp-AkRN8Zur9Nt_qAn5SxFzdiWAogOhhk4Fo0h58',
            badge: 'Más Vendida',
            badgeColor: 'primary',
            rating: 4.9,
            calories: 840,
            ingredients: [
                'Doble carne de res',
                'Queso Cheddar',
                'Lechuga Crujiente',
                'Tomates madurados en vid',
                'Pepinillos en vinagre',
                'Salsa Secreta de la Casa',
            ],
        },
        {
            id: '2',
            name: 'Hamburguesa Doble Queso',
            description: 'Dos carnes de res a la parrilla, el doble de queso, cebollas y pepinillos.',
            price: 16.49,
            image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAEoXzrL31KpXUK9BybW0mvI-3RxWZWNKh_q9CEzNSeRjzu4YLao4idxgN_HG-SghYBsqw20np-65QsUgjI-uJUrm6rprj7--xkKpcx25-6Zpfe1E6Kl87chyXTWhw1yprO7raYD-7nHjQMh6frJQ8Ci_9lAxvrLqX-2nlncSrlj_Szos-EolFrWWkD_TDO4NIMspwGH8DhMGdEVXAIFc_KjVxwfq-iLe0tPeQn4zPJwXZZJLzhD09bUsmtxKldYgiMyv4xkXDPlTg',
            rating: 4.8,
            calories: 920,
            ingredients: [
                'Doble carne de res',
                'Queso Cheddar',
                'Lechuga Crujiente',
                'Tomates madurados en vid',
                'Pepinillos en vinagre',
                'Salsa Secreta de la Casa',
            ],
        },
        {
            id: '3',
            name: 'Bacon Deluxe',
            description: 'Tocineta crujiente al arce, cebollas caramelizadas, queso gouda ahumado en pan brioche.',
            price: 15.99,
            image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBdfcZ28n1UP8eiyxAl2jy_A04xnpDf9U1agZtuDh4m5xHyHAHVQFDXAeoIuZ-HUamnM3ZXo01awMIsQumH9BVeEGbTNH9YfMeGp5owjvrY2u49iM9GNkLM5Ldn5v4u4QwuzG-tXTTSjQJzEc219T-szOOPlI61GnznGEcHY0OIvfMNm6MMXKdRLrvIXVgb7CFaL8Us4gi_1lMtHDywL5yL_hTi1Jwxd2K9rvrEp-AkRN8Zur9Nt_qAn5SxFzdiWAogOhhk4Fo0h58',
            rating: 4.7,
            calories: 880,
            ingredients: [
                'Carne de Res',
                'Tocineta al Arce',
                'Queso Gouda Ahumado',
                'Cebollas Caramelizadas',
                'Pan Brioche',
                'Salsa Especial',
            ],
        },
        {
            id: '4',
            name: 'Veggie de la Huerta',
            description: 'Hamburguesa de quinoa y batata, puré de aguacate y brotes frescos.',
            price: 13.50,
            image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAEoXzrL31KpXUK9BybW0mvI-3RxWZWNKh_q9CEzNSeRjzu4YLao4idxgN_HG-SghYBsqw20np-65QsUgjI-uJUrm6rprj7--xkKpcx25-6Zpfe1E6Kl87chyXTWhw1yprO7raYD-7nHjQMh6frJQ8Ci_9lAxvrLqX-2nlncSrlj_Szos-EolFrWWkD_TDO4NIMspwGH8DhMGdEVXAIFc_KjVxwfq-iLe0tPeQn4zPJwXZZJLzhD09bUsmtxKldYgiMyv4xkXDPlTg',
            badge: 'A base de plantas',
            badgeColor: 'emerald',
            rating: 4.6,
            calories: 620,
            ingredients: [
                'Carne de Quinoa',
                'Batata',
                'Puré de Aguacate',
                'Brotes Frescos',
                'Tomates',
                'Pan Integral',
            ],
        },
        {
            id: '5',
            name: 'Jalapeño Picante',
            description: 'Queso pepper jack, jalapeños frescos y alioli de habanero. Para los valientes.',
            price: 14.25,
            image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBdfcZ28n1UP8eiyxAl2jy_A04xnpDf9U1agZtuDh4m5xHyHAHVQFDXAeoIuZ-HUamnM3ZXo01awMIsQumH9BVeEGbTNH9YfMeGp5owjvrY2u49iM9GNkLM5Ldn5v4u4QwuzG-tXTTSjQJzEc219T-szOOPlI61GnznGEcHY0OIvfMNm6MMXKdRLrvIXVgb7CFaL8Us4gi_1lMtHDywL5yL_hTi1Jwxd2K9rvrEp-AkRN8Zur9Nt_qAn5SxFzdiWAogOhhk4Fo0h58',
            rating: 4.5,
            calories: 870,
            ingredients: [
                'Carne de Res',
                'Queso Pepper Jack',
                'Jalapeños Frescos',
                'Alioli de Habanero',
                'Lechuga',
                'Pan de Sésamo',
            ],
        },
        {
            id: '6',
            name: 'Champiñones y Suizo',
            description: 'Champiñones portobello salteados y queso suizo derretido en pan de semillas de amapola.',
            price: 14.99,
            image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAEoXzrL31KpXUK9BybW0mvI-3RxWZWNKh_q9CEzNSeRjzu4YLao4idxgN_HG-SghYBsqw20np-65QsUgjI-uJUrm6rprj7--xkKpcx25-6Zpfe1E6Kl87chyXTWhw1yprO7raYD-7nHjQMh6frJQ8Ci_9lAxvrLqX-2nlncSrlj_Szos-EolFrWWkD_TDO4NIMspwGH8DhMGdEVXAIFc_KjVxwfq-iLe0tPeQn4zPJwXZZJLzhD09bUsmtxKldYgiMyv4xkXDPlTg',
            rating: 4.7,
            calories: 790,
            ingredients: [
                'Carne de Res',
                'Queso Suizo',
                'Champiñones Portobello',
                'Cebollas Caramelizadas',
                'Pan de Amapola',
                'Alioli de Ajo',
            ],
        },
    ],
}
